from pathlib import Path

dir_path = Path(r"path-to-project")
ignored_files: list[str] = [
    ".venv",
    ".git",
    ".env",
]


def tree(dir_path: Path, prefix: str = ""):
    """A recursive generator, given a directory Path object
    will yield a visual tree structure line by line
    with each line prefixed by the same characters

    Args:
        dir_path: Path of the project
        prefix: Prefix if declared
    """
    SPACE = "    "
    PIPE = "│   "
    TEE = "├── "
    ELBOW = "└── "

    contents = []
    for folder in list(dir_path.iterdir()):
        if str(folder).split("\\")[-1] not in ignored_files:
            contents.append(folder)
    pointers = [TEE] * (len(contents) - 1) + [ELBOW]
    for pointer, path in zip(pointers, contents):
        yield prefix + pointer + path.name
        if path.is_dir():
            extension = PIPE if pointer == TEE else SPACE
            yield from tree(path, prefix=prefix + extension)


def create_tree(dir_path: Path) -> None:
    """Print out the tree structure of project which generated by tree function

    Args:
        dir_path: Path of the project
    """
    print(str(dir_path).split("\\")[-1])
    for line in tree(dir_path):
        print(line)


create_tree(dir_path)
